### ISSUE TITLE
Last item is not visible

### ISSUE THREAD

**Issue by lmachens** [neuefische/css-teams-team_4#4]
It's not possible to show the last item in the main area, because the footer is always in front of it:

![image](https://user-images.githubusercontent.com/10058950/68203715-b8c47100-ffc6-11e9-941c-9572c9950628.png)

You have at least two options:

- add a margin-bottom to the main area
- don't make the footer position absolute

**Comment by manuelwecker** [comment]
Thanks for your review and hint. We solved the problem using the first solution. See below:
<img width="830" alt="Bildschirmfoto 2019-11-08 um 15 26 43" src="https://user-images.githubusercontent.com/56833780/68483638-393fd780-023c-11ea-9180-3390dc1d21e0.png">
